### ISSUE TITLE
전달 인자(o,x) 반환값(o,x) 함수 

### ISSUE THREAD

**Issue by minseo-jung** [minseo-jung/study-c#12]
아직 반환이나 그런 개념이 부족해서 인지 정확한 차이라던가 그런걸 잘 모르겠어요 제가 만든 피보나치 함수도 저는 void로 올렸지만 int로 바꿔도 실행이 되기도 하고 아직 그런차이가 와 닿지가 않습니다

**Comment by wonny25** [comment]
함수쪽을 다루게 되면 될건데
이번주에 만나면 계산기를 한번 같이 만들면서 연습해보자.
