### ISSUE TITLE
곱셈 기능을 지니는 함수를 구현 하여 0 0을 입력전까지 곱셈하고 총 연산횟수 알려주는 함수 구현하기

### ISSUE THREAD

**Issue by minseo-jung** [minseo-jung/study-c#13]
```
#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>

int multiple(int a, int b);
void p9_2_1()
{
	int a=1, b=1;
	int c = 0;
	
	for(; !(a&&b) == 0; c++)
	{	
		printf("두 개의 숫자 입력:\n");
		scanf("%d %d", &a, &b);
		printf("연산 결과: %d\n", multiple(a, b));
	}
			
	printf("총 %d번 연산하였습니다", c);

	return 0;


}

int multiple(int a, int b)
{
	return a * b;
}
```

**Comment by wonny25** [comment]
`0 0` 을 입력하면 프로그램 종료되는걸 기대하고 for문에 조건으로 넣은거야?

**Comment by minseo-jung** [comment]
-----Original Message-----
보낸사람: "wonny25" <notifications@github.com>
받는사람: "minseo-jung/study-c" <study-c@noreply.github.com>
참조: "minseo-jung" <minse1752@naver.com>,"Author" <author@noreply.github.com>
날짜: 2019.07.18 오전 11:19:21 (GMT+09:00)
제목: Re: [minseo-jung/study-c] 곱셈 기능을 지니는 함수를 구현 하여 0 0을 입력전까지 곱셈하고 총 연산횟수 알려주는 함수 구현하기 (#13)

0 0 을 입력하면 프로그램 종료되는걸 기대하고 for문에 조건으로 넣은거야?
